"""CREATE_USER_TABLE

Revision ID: 865df9533ff0
Revises: 
Create Date: 2024-10-30 13:03:45.923716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865df9533ff0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户账号'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='用户密码'),
    sa.Column('nickname', sa.String(length=32), nullable=False, comment='用户昵称'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='用户头像url'),
    sa.Column('background', sa.String(length=500), nullable=True, comment='主页背景图url'),
    sa.Column('gender', sa.SmallInteger(), nullable=False, comment='性别 0女 1男 2未知'),
    sa.Column('description', sa.String(length=100), nullable=True, comment='个性签名'),
    sa.Column('exp', sa.Integer(), nullable=False, comment='经验值'),
    sa.Column('coin', sa.Float(), nullable=False, comment='硬币数'),
    sa.Column('vip', sa.SmallInteger(), nullable=False, comment='会员类型 0普通用户 1月度大会员 2季度大会员 3年度大会员'),
    sa.Column('state', sa.SmallInteger(), nullable=False, comment='状态 0正常 1封禁 2注销'),
    sa.Column('role', sa.SmallInteger(), nullable=False, comment='角色类型 0普通用户 1管理员 2超级管理员'),
    sa.Column('auth', sa.SmallInteger(), nullable=False, comment='官方认证 0普通用户 1个人认证 2机构认证'),
    sa.Column('auth_msg', sa.String(length=30), nullable=True, comment='认证说明'),
    sa.Column('create_date', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('delete_date', sa.DateTime(), nullable=True, comment='注销时间'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
